"""Constants used across the Oracle ARM Manager application."""

# Notification Colors
COLOR_SUCCESS_HEX = "#00ff00"
COLOR_FAIL_HEX = "#ff0000"
COLOR_DISCORD_SUCCESS_INT = 65280
COLOR_DISCORD_FAIL_INT = 16711680

# HTTP and API Constants
HTTP_TIMEOUT_SECONDS = 15
OCI_API_TIMEOUT_SECONDS = 60
HTTP_RETRY_STATUS_FORCELIST = [500, 502, 503, 504]
HTTP_MAX_RETRIES = 3

# Default OCI Resource Values
DEFAULT_OCPUS = 4.0
DEFAULT_MEMORY_GBS = 24.0
DEFAULT_BOOT_VOLUME_SIZE = 50
DEFAULT_BOOT_VOLUME_VPUS = 10
DEFAULT_MAX_INSTANCES = 1
DEFAULT_COST_THRESHOLD = 0.1
DEFAULT_SHAPE = "VM.Standard.A1.Flex"

# Validation Thresholds
MIN_BOOT_VOLUME_SIZE = 50
MIN_OCPUS = 1.0
MIN_MEMORY_GBS = 6.0

# API Keywords
CAPACITY_KEYWORDS = ["capacity", "quota", "limit"]
